# 1️⃣ Разработчик загружает приложение
POST http://localhost:8080/api/developer/applications?developerId=1
Content-Type: application/json

{
  "name": "My App",
  "description": "This is a test app",
  "appFilePath": "amogus.ru/uploads/myapp.apk"
}

###

# 2️⃣ Получаем список приложений разработчика
GET http://localhost:8080/api/developer/applications?developerId=1&page=0&size=10

###

# 3️⃣ Модератор проверяет приложение (одобряет)
POST http://localhost:8080/api/moderator/applications/1/review?approved=true

###

# 4️⃣ Разработчику предлагают монетизацию (он может отказаться или сразу подключить)
# Если разработчик отказывается, пропустить следующий шаг

POST http://localhost:8080/api/developer/applications/1/monetization/request?developerId=1&accountNumber=1234567890


###

# 5️⃣ Финансовый отдел проверяет реквизиты (может отклонить)
POST http://localhost:8080/api/finance/paymentinfo/1/validate?paymentStatus=REJECTED

###

# 6️⃣ Разработчик исправляет реквизиты и снова отправляет
POST http://localhost:8080/api/developer/applications/1/monetization/request?developerId=1&accountNumber=2134567890
###

# 7️⃣ Финансовый отдел повторно проверяет реквизиты (утверждает)
POST http://localhost:8080/api/finance/paymentinfo/1/validate?paymentStatus=APPROVED

###

# 8️⃣ Финансовый отдел создаёт договор
POST http://localhost:8080/api/finance/contracts?applicationId=1&pdfPath=/path/to/contract.pdf

###

# 9️⃣ Разработчик подписывает договор (или отказывается)
# Если разработчик отказывается, пропустите следующий шаг
GET http://localhost:8080/api/developer/contracts/1&page=0&size=10

###
# ыыы
POST http://localhost:8080/api/developer/contracts/1/response?developerId=1&accepted=true

###

# 🔟 Разработчик останавливает монетизацию
POST http://localhost:8080/api/developer/applications/1/monetization/stop?developerId=1

###

# 1️⃣1️⃣ Разработчик обновляет приложение
PUT http://localhost:8080/api/developer/applications/1?developerId=1
Content-Type: application/json

{
  "name": "Updated My App",
  "description": "Updated description",
  "appFilePath": "amogus.ru/uploads/myapp.apk"
}

###

# 1️⃣2️⃣ Разработчик удаляет приложение
DELETE http://localhost:8080/api/developer/applications/1?developerId=1
