version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: google_play_db
    restart: always
    environment:
      POSTGRES_DB: google_play_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - google_play_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgAdmin для управления базой
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - google_play_network
    depends_on:
      - postgres

#  # Spring Boot Application
#  google_play_app:
#    build: .
#    container_name: google_play_app
#    restart: always
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/google_play_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    ports:
#      - "8080:8080"
#    networks:
#      - google_play_network
#    depends_on:
#      - postgres

networks:
  google_play_network:
    driver: bridge

volumes:
  pgdata:
