services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: google_play_db
    restart: always
    environment:
      POSTGRES_DB: google_play_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - google_play_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres_contracts:
    image: postgres:14
    container_name: contracts_db
    restart: always
    environment:
      POSTGRES_DB: contracts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - google_play_network
    volumes:
      - pgdata_contracts:/var/lib/postgresql/data

networks:
  google_play_network:
    driver: bridge

volumes:
  pgdata:
  pgdata_contracts:
